import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans_JP } from "next/font/google"
import { cn } from "@/lib/utils"
const noto = Noto_Sans_JP({ weight: ['400', '700'], subsets: ['latin'], variable: '--font-noto' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log('cn("font-sans", noto.variable)', cn("font-sans", noto.variable))
  return (
    <html lang="en">
      <body className={cn("font-sans", noto.variable)}>{children}</body>
    </html>
  )
}
